---
title: "Drawing Figure for manuscript"
author: "incheol, hyunsu"
date: "July 27, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data load
```{r, message=FALSE, warning=FALSE}
setwd("../Data_prep/divided_revised_data")

cre_na_omitted <- read.csv("cre_na_omitted.csv", row.names = "X")


Btrain		<- read.csv("Btrain.csv", row.names = "X")
Btrain.l	<- read.csv("Btrain_long.csv", header = T, row.names = "X")
Btrain.s	<- read.csv("Btrain_short.csv", header = T, row.names = "X")
Btrain.r	<- read.csv("Btrain_ramp.csv", header = T, row.names = "X")

Btest		<- read.csv("Btest.csv", row.names = "X")
Btest.l		<- read.csv("Btest_long.csv", header = T, row.names = "X")
Btest.s		<- read.csv("Btest_short.csv", header = T, row.names = "X")
Btest.r		<- read.csv("Btest_ramp.csv", header = T, row.names = "X")

Etrain		<- read.csv("Etrain.csv", row.names = "X")
Etrain.l	<- read.csv("Etrain_long.csv", header = T, row.names = "X")
Etrain.s	<- read.csv("Etrain_short.csv", header = T, row.names = "X")
Etrain.r	<- read.csv("Etrain_ramp.csv", header = T, row.names = "X")

Etest		<- read.csv("Etest.csv", row.names = "X")
Etest.l		<- read.csv("Etest_long.csv", header = T, row.names = "X")
Etest.s		<- read.csv("Etest_short.csv", header = T, row.names = "X")
Etest.r		<- read.csv("Etest_ramp.csv", header = T, row.names = "X")

Itrain		<- read.csv("Itrain.csv", row.names = "X")
Itrain.l	<- read.csv("Itrain_long.csv", header = T, row.names = "X")
Itrain.s	<- read.csv("Itrain_short.csv", header = T, row.names = "X")
Itrain.r	<- read.csv("Itrain_ramp.csv", header = T, row.names = "X")

Itest		<- read.csv("Itest.csv", row.names = "X")
Itest.l		<- read.csv("Itest_long.csv", header = T, row.names = "X")
Itest.s		<- read.csv("Itest_short.csv", header = T, row.names = "X")
Itest.r		<- read.csv("Itest_ramp.csv", header = T, row.names = "X")

Ltrain		<- read.csv("Ltrain.csv", row.names = "X")
Ltrain.l	<- read.csv("Ltrain_long.csv", header = T, row.names = "X")
Ltrain.s	<- read.csv("Ltrain_short.csv", header = T, row.names = "X")
Ltrain.r	<- read.csv("Ltrain_ramp.csv", header = T, row.names = "X")

Ltest		<- read.csv("Ltest.csv", row.names = "X")
Ltest.l		<- read.csv("Ltest_long.csv", header = T, row.names = "X")
Ltest.s		<- read.csv("Ltest_short.csv", header = T, row.names = "X")
Ltest.r		<- read.csv("Ltest_ramp.csv", header = T, row.names = "X")
```


# Binary classification

## Load ANN results
```{r, message=FALSE, warning=FALSE}
setwd("../ANN/revised_results")

E.ANN.full <-read.csv("04_4_Eline_full_argmax.csv",header=F) 
E.ANN.long <-read.csv("05_4_Eline_long_argmax.csv",header=F)
E.ANN.short<-read.csv("06_4_Eline_short_argmax.csv",header=F)
E.ANN.ramp <-read.csv("07_4_Eline_ramp_argmax.csv",header=F)

I.ANN.full <-read.csv("08_4_Iline_full_argmax.csv",header=F) 
I.ANN.long <-read.csv("09_4_Iline_long_argmax.csv",header=F)
I.ANN.short<-read.csv("10_4_Iline_short_argmax.csv",header=F)
I.ANN.ramp <-read.csv("11_4_Iline_ramp_argmax.csv",header=F)

L.ANN.full <-read.csv("12_4_Lline_full_argmax.csv",header=F) 
L.ANN.long <-read.csv("13_4_Lline_long_argmax.csv",header=F)
L.ANN.short<-read.csv("14_4_Lline_short_argmax.csv",header=F)
L.ANN.ramp <-read.csv("15_4_Lline_ramp_argmax.csv",header=F)
```

# Load LASSO and RF models
```{r, message=FALSE, warning=FALSE}
setwd("../lasso_rf/")

model_files <- list.files("./R_models/")

for (file_name in model_files){
  load(paste0("./R_models/",file_name))
} 


```



# Draw Figure 4 classification for E tf line(merged) 
# confusion matrix and accuracy bar plot
```{r, message=FALSE, warning=FALSE}
require(ggplot2)
library(ROCR)
library(magrittr)
library(caret)
require(gridExtra)
library(reshape2)
library(dplyr)
library(scales)



fig5 <-list()
fig5data <- list()
percent.matrix <- list()
count.matrix <- list()
Eline_name <- c("Ctgf", "Cux2&Slc17a6","Nr5a1&Scnn1a","Ntsr1","Rbp4","Rorb")

models <- c("ANN", "reg", "rf")
input <- c("full", "long", "short", "ramp")

E.ANN.full.char <- as.character(E.ANN.full[,1]+1)
E.ANN.long.char <- as.character(E.ANN.long[,1]+1)
E.ANN.short.char <- as.character(E.ANN.short[,1]+1)
E.ANN.ramp.char <- as.character(E.ANN.ramp[,1]+1)
for(i in 1:10) {
  E.ANN.full.char[E.ANN.full.char == as.character(i)] <- as.character(levels(Etrain$transgenic_line)[i])
  E.ANN.long.char[E.ANN.long.char == as.character(i)] <- as.character(levels(Etrain$transgenic_line)[i])
  E.ANN.short.char[E.ANN.short.char == as.character(i)] <- as.character(levels(Etrain$transgenic_line)[i])
  E.ANN.ramp.char[E.ANN.ramp.char == as.character(i)] <- as.character(levels(Etrain$transgenic_line)[i])
    }

accu_E <- NA

for(i in 1:3) {
  if (models[i] == "ANN") {
    for(j in 1:4) {
      modelname <- paste0("E.",models[i],".",input[j],".char")
      model <- get(modelname)
      model_factor <- factor(model, levels = levels(Etrain$transgenic_line))
      cm_table <- confusionMatrix(model_factor, Etest$transgenic_line)
      fig5data[[j]] <- mutate(group_by(as.data.frame(cm_table$table), Reference),
                              percentage = Freq/sum(Freq)*100)
      accu_each <- as.data.frame(cm_table$overall[c(1, 3:4)])
      accu_each <- rbind.data.frame(accu_each, models[i], input[j])
      colnames(accu_each) <- modelname
      accu_E <- cbind.data.frame(accu_E, accu_each)
      }
    }
  else {
      for(j in 1:4) {
        modelname <- (paste0("E.",models[i], ".", input[j],".nocv"))
        model <- get(modelname)
        cm_table <- confusionMatrix(predict(model, newdata = Etest), Etest$transgenic_line)
        fig5data[[j+(4*(i-1))]] <- mutate(group_by(as.data.frame(cm_table$table), Reference),
                              percentage = Freq/sum(Freq)*100)
        accu_each <- as.data.frame(cm_table$overall[c(1, 3:4)])
        accu_each <- rbind.data.frame(accu_each, models[i], input[j])
        colnames(accu_each) <- modelname
        accu_E <- cbind.data.frame(accu_E, accu_each)
        }
  }
}




for(i in 1:12){
  fig5[[i]]<-ggplot(data = fig5data[[i]],aes(x=Prediction, y=Reference),
                    fill=percentage) + geom_tile(aes(fill=percentage)) +
  scale_y_discrete(limits = rev(levels(fig5data[[i]]$Reference)), labels=rev(Eline_name), position = "right") +
  scale_x_discrete(labels=Eline_name)  +
  scale_fill_gradient2(mid = "lightgoldenrodyellow", high = "firebrick2")+geom_text(label=fig5data[[i]]$Freq) + theme(plot.title = element_blank(),
          axis.title = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank(), 
          panel.background = element_blank(), 
          legend.position = "none") 
}

fig5[[1]] <- fig5[[1]] + scale_x_discrete(position = "top") + scale_y_discrete(limits = rev(levels(fig5data[[i]]$Reference)), labels=rev(Eline_name), position = "left") + labs(x = "Full", y = "ANN") + theme(axis.title = element_text(size = rel(1.5)))
fig5[[2]] <- fig5[[2]] + scale_x_discrete(position = "top")+labs(x = "Long") + theme(axis.title = element_text(size = rel(1.5)), axis.title.y = element_blank())
fig5[[3]] <- fig5[[3]] + scale_x_discrete(position = "top")+labs(x = "Short") + theme(axis.title = element_text(size = rel(1.5)), axis.title.y = element_blank())
fig5[[4]] <- fig5[[4]] + scale_x_discrete(position = "top")+labs(x = "Ramp") + theme(axis.title = element_text(size = rel(1.5)), axis.title.y = element_blank(), axis.ticks.y.right = element_line(), axis.text.y.right = element_text(hjust=0, vjust = 0.5))

fig5[[5]] <- fig5[[5]] + scale_y_discrete(limits = rev(levels(fig5data[[i]]$Reference)), labels=rev(Eline_name), position = "left") + labs(y = "LASSO") + theme(axis.title = element_text(size = rel(1.5)), axis.title.x = element_blank())

fig5[[8]] <- fig5[[8]] + theme(axis.ticks.y.right = element_line(), axis.text.y.right = element_text(hjust=0, vjust = 0.5))

fig5[[9]] <- fig5[[9]] + scale_y_discrete(limits = rev(levels(fig5data[[i]]$Reference)), labels=rev(Eline_name), position = "left") + labs(y = "RF") + scale_x_discrete(labels=Eline_name, position = "bottom") + theme(axis.title = element_text(size = rel(1.5)), axis.title.x = element_blank(), axis.ticks.x= element_line(), axis.text.x = element_text(hjust=1, vjust = 0.5, angle = 90))

fig5[[10]] <- fig5[[10]] + scale_x_discrete(labels=Eline_name, position = "bottom") + theme(axis.ticks.x= element_line(), axis.text.x = element_text(hjust=1, vjust = 0.5, angle = 90))
fig5[[11]] <- fig5[[11]] + scale_x_discrete(labels=Eline_name, position = "bottom") + theme(axis.ticks.x= element_line(), axis.text.x = element_text(hjust=1, vjust = 0.5, angle = 90))

fig5[[12]] <- fig5[[12]] + scale_x_discrete(labels=Eline_name, position = "bottom") + theme(axis.ticks.x= element_line(), axis.text.x = element_text(hjust=1, vjust = 0.5, angle = 90), axis.ticks.y.right = element_line(), axis.text.y.right = element_text(hjust=0, vjust = 0.5)) 

legend_fig <- fig5[[12]] + scale_x_discrete(labels=Eline_name, position = "bottom") + theme(axis.ticks.x= element_line(), axis.text.x = element_text(hjust=1, vjust = 0.5, angle = 90), axis.ticks.y.right = element_line(), axis.text.y.right = element_text(hjust=0, vjust = 0.5)) + theme(legend.position = "right")


fig5_u_grob <-lapply(fig5, ggplotGrob)
fig5_u_grob
fig5_cm <- grid.arrange(grobs = fig5_u_grob, ncol = 4, nrow = 3, heights = c(1,0.9,1.4), widths = c(1, 0.9, 0.9, 1.3))

ggsave("fig4cm.tiff", fig5_cm, width = 12, height = 7, units = "in", dpi = 300)
ggsave("fig4_for_legend.tiff", legend_fig, width = 6, height = 6, units = "in", dpi = 300)



# Accruay bar chart, accurary date was collected above for-loop

accu_E <- cbind.data.frame(accu_E[2:13])
accu_E <- as.data.frame(t(accu_E))
colnames(accu_E) <- c("Accuracy", "LowCI", "UpCI", "Model", "Input")
accu_E$Accuracy <- as.numeric(as.character(accu_E$Accuracy))
accu_E$LowCI <- as.numeric(as.character(accu_E$LowCI))
accu_E$UpCI <- as.numeric(as.character(accu_E$UpCI))
accu_E$Input <- factor(accu_E$Input, levels(accu_E$Input)[c(1,2,4,3)]) # reorder levels of input from alphabetical to experimental, to match with previous curves
levels(accu_E$Model) <- c("ANN", "LASSO", "RF")
levels(accu_E$Input) <- c("Full", "Long", "Short", "Ramp")

fig5_b <- ggplot(data = accu_E, aes(Input, Accuracy, fill = Model)) + 
  geom_bar(stat = "identity", color = "black", position = position_dodge()) +
  geom_errorbar(aes(ymin= LowCI, ymax = UpCI), width= 0.2, position = position_dodge(0.9)) +

  theme_classic() + 
               labs(x = "", y = "Accuracy") +
                 theme(legend.position = "bottom",
                       legend.title = element_blank(),
                       legend.margin=margin(t=-0.7, unit='cm'), 
                       legend.text = element_text(margin = margin(l = 5, r = 10, unit = "pt"))) +
               scale_fill_brewer( palette = "Set1")

ggsave("fig4accubar.tiff", fig5_b, width = 12, height = 7, units = "in", dpi = 300)


fig5 <- grid.arrange(fig5_cm, fig5_b, ncol = 1, heights = c(2,1))

ggsave("fig4.tiff", fig5, width = 12, height = 10, units = "in", dpi = 300)
                          
```


# Draw Figure 5 classification for I tf line(merged), 
# confusion matrix and accuracy bar plot
```{r, message=FALSE, warning=FALSE}
require(ggplot2)
library(ROCR)
library(magrittr)
library(caret)
require(gridExtra)
library(reshape2)


fig6 <-list()
fig6data <- list()
# levels(Itrain$transgenic_line)

Iline_name <- c("Chrna2","Gad2","Htr3a","Ndnf", "Nkx2.1","Pvalb","Sst","Vip")

models <- c("ANN", "reg", "rf")
input <- c("full", "long", "short", "ramp")


I.ANN.full.char <- as.character(I.ANN.full[,1]+1)
I.ANN.long.char <- as.character(I.ANN.long[,1]+1)
I.ANN.short.char <- as.character(I.ANN.short[,1]+1)
I.ANN.ramp.char <- as.character(I.ANN.ramp[,1]+1)
for(i in 1:10) {
  I.ANN.full.char[I.ANN.full.char == as.character(i)] <- as.character(levels(Itrain$transgenic_line)[i])
  I.ANN.long.char[I.ANN.long.char == as.character(i)] <- as.character(levels(Itrain$transgenic_line)[i])
  I.ANN.short.char[I.ANN.short.char == as.character(i)] <- as.character(levels(Itrain$transgenic_line)[i])
  I.ANN.ramp.char[I.ANN.ramp.char == as.character(i)] <- as.character(levels(Itrain$transgenic_line)[i])
  
  }

accu_I <- NA

for(i in 1:3) {
  if (models[i] == "ANN") {
    for(j in 1:4) {
      modelname <- paste0("I.",models[i],".",input[j],".char")
      model <- get(modelname)
      model_factor <- factor(model, levels = levels(Itrain$transgenic_line))
      cm_table <- confusionMatrix(model_factor, Itest$transgenic_line)
      fig6data[[j]] <- mutate(group_by(as.data.frame(cm_table$table), Reference),
                              percentage = Freq/sum(Freq)*100)
      accu_each <- as.data.frame(cm_table$overall[c(1, 3:4)])
      accu_each <- rbind.data.frame(accu_each, models[i], input[j])
      colnames(accu_each) <- modelname
      accu_I <- cbind.data.frame(accu_I, accu_each)
      }
    }
  else {
      for(j in 1:4) {
        modelname <- (paste0("I.",models[i], ".", input[j],".nocv"))
        model <- get(modelname)
        cm_table <- confusionMatrix(predict(model, newdata = Itest), Itest$transgenic_line)
        fig6data[[j+(4*(i-1))]] <- mutate(group_by(as.data.frame(cm_table$table), Reference),
                              percentage = Freq/sum(Freq)*100)
        accu_each <- as.data.frame(cm_table$overall[c(1, 3:4)])
        accu_each <- rbind.data.frame(accu_each, models[i], input[j])
        colnames(accu_each) <- modelname
        accu_I <- cbind.data.frame(accu_I, accu_each)
        }
  }
}


for(i in 1:12){
  fig6[[i]]<-ggplot(data = fig6data[[i]],aes(x=Prediction, y=Reference), fill=percentage) + geom_tile(aes(fill=percentage)) +
  scale_y_discrete(limits = rev(levels(fig6data[[i]]$Reference)), labels=rev(Iline_name), position = "right") +
  scale_x_discrete(labels=Iline_name)  +
  scale_fill_gradient2(mid = "lightgoldenrodyellow", high = "firebrick2")+geom_text(label=fig6data[[i]]$Freq) + theme(plot.title = element_blank(),
          axis.title = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank(), 
          panel.background = element_blank(), 
          legend.position = "none") 
}

fig6[[1]] <- fig6[[1]] + scale_x_discrete(position = "top") + scale_y_discrete(limits = rev(levels(fig6data[[i]]$Reference)), labels=rev(Iline_name), position = "left") + labs(x = "Full", y = "ANN") + theme(axis.title = element_text(size = rel(1.5)))
fig6[[2]] <- fig6[[2]] + scale_x_discrete(position = "top")+labs(x = "Long") + theme(axis.title = element_text(size = rel(1.5)), axis.title.y = element_blank())
fig6[[3]] <- fig6[[3]] + scale_x_discrete(position = "top")+labs(x = "Short") + theme(axis.title = element_text(size = rel(1.5)), axis.title.y = element_blank())
fig6[[4]] <- fig6[[4]] + scale_x_discrete(position = "top")+labs(x = "Ramp") + theme(axis.title = element_text(size = rel(1.5)), axis.title.y = element_blank(), axis.ticks.y.right = element_line(), axis.text.y.right = element_text(hjust=0, vjust = 0.5))

fig6[[5]] <- fig6[[5]] + scale_y_discrete(limits = rev(levels(fig6data[[i]]$Reference)), labels=rev(Iline_name), position = "left") + labs(y = "LASSO") + theme(axis.title = element_text(size = rel(1.5)), axis.title.x = element_blank())

fig6[[8]] <- fig6[[8]] + theme(axis.ticks.y.right = element_line(), axis.text.y.right = element_text(hjust=0, vjust = 0.5))

fig6[[9]] <- fig6[[9]] + scale_y_discrete(limits = rev(levels(fig6data[[i]]$Reference)), labels=rev(Iline_name), position = "left") + labs(y = "RF") + scale_x_discrete(labels=Iline_name, position = "bottom") + theme(axis.title = element_text(size = rel(1.5)), axis.title.x = element_blank(), axis.ticks.x= element_line(), axis.text.x = element_text(hjust=1, vjust = 0.5, angle = 90))

fig6[[10]] <- fig6[[10]] + scale_x_discrete(labels=Iline_name, position = "bottom") + theme(axis.ticks.x= element_line(), axis.text.x = element_text(hjust=1, vjust = 0.5, angle = 90))
fig6[[11]] <- fig6[[11]] + scale_x_discrete(labels=Iline_name, position = "bottom") + theme(axis.ticks.x= element_line(), axis.text.x = element_text(hjust=1, vjust = 0.5, angle = 90))

fig6[[12]] <- fig6[[12]] + scale_x_discrete(labels=Iline_name, position = "bottom") + theme(axis.ticks.x= element_line(), axis.text.x = element_text(hjust=1, vjust = 0.5, angle = 90), axis.ticks.y.right = element_line(), axis.text.y.right = element_text(hjust=0, vjust = 0.5))

fig6_u_grob <-lapply(fig6, ggplotGrob)
fig6_u_grob
fig6_cm <- grid.arrange(grobs = fig6_u_grob, ncol = 4, nrow = 3, heights = c(1,0.9,1.2), widths = c(1, 0.9, 0.9, 1.1))

ggsave("fig5cm.tiff", fig6_cm, width = 12, height = 7, units = "in", dpi = 300)




# Accruay bar chart, accurary date was collected above for-loop

accu_I <- cbind.data.frame(accu_I[2:13])
accu_I <- as.data.frame(t(accu_I))
colnames(accu_I) <- c("Accuracy", "LowCI", "UpCI", "Model", "Input")
accu_I$Accuracy <- as.numeric(as.character(accu_I$Accuracy))
accu_I$LowCI <- as.numeric(as.character(accu_I$LowCI))
accu_I$UpCI <- as.numeric(as.character(accu_I$UpCI))
accu_I$Input <- factor(accu_I$Input, levels(accu_I$Input)[c(1,2,4,3)]) # reorder levels of input from alphabetical to experimental, to match with previous curves
levels(accu_I$Model) <- c("ANN", "LASSO", "RF")
levels(accu_I$Input) <- c("Full", "Long", "Short", "Ramp")

fig6_b <- ggplot(data = accu_I, aes(Input, Accuracy, fill = Model)) + 
  geom_bar(stat = "identity", color = "black", position = position_dodge()) +
  geom_errorbar(aes(ymin= LowCI, ymax = UpCI), width= 0.2, position = position_dodge(0.9)) +

  theme_classic() + 
               labs(x = "", y = "Accuracy") +
               theme(legend.position = "bottom",
                     legend.title = element_blank(),
                     legend.margin=margin(t=-0.7, unit='cm'), 
                     legend.text = element_text(margin = margin(l = 5, r = 10, unit = "pt"))) +
               scale_fill_brewer( palette = "Set1")

ggsave("fig5accubar.tiff", fig6_b, width = 12, height = 7, units = "in", dpi = 300)


fig6 <- grid.arrange(fig6_cm, fig6_b, ncol = 1, heights = c(2,1))

ggsave("fig5.tiff", fig6, width = 12, height = 10, units = "in", dpi = 300)
```


# Draw Figure 6 classification for Layer exci tf line, 
# confusion matrix and accuracy bar plot
```{r, message=FALSE, warning=FALSE}
require(ggplot2)
library(ROCR)
library(magrittr)
library(caret)
require(gridExtra)
library(reshape2)
library(dplyr)


fig7 <-list()
fig7data <- list()

percent.matrix <- list()
count.matrix <- list()


levels(Ltrain$L_tg)

Lline_name <- c("L2/3_Cre","L4_Cre","L5_Cre","L6a_Cre", "L6b_Cre")

models <- c("ANN", "reg", "rf")
input <- c("full", "long", "short", "ramp")


L.ANN.full.char <- as.character(L.ANN.full[,1]+1)
L.ANN.long.char <- as.character(L.ANN.long[,1]+1)
L.ANN.short.char <- as.character(L.ANN.short[,1]+1)
L.ANN.ramp.char <- as.character(L.ANN.ramp[,1]+1)
for(i in 1:10) {
  L.ANN.full.char[L.ANN.full.char == as.character(i)] <- as.character(levels(Ltrain$L_tg)[i])
  L.ANN.long.char[L.ANN.long.char == as.character(i)] <- as.character(levels(Ltrain$L_tg)[i])
  L.ANN.short.char[L.ANN.short.char == as.character(i)] <- as.character(levels(Ltrain$L_tg)[i])
  L.ANN.ramp.char[L.ANN.ramp.char == as.character(i)] <- as.character(levels(Ltrain$L_tg)[i])
  
  }

accu_L <- NA

for(i in 1:3) {
  if (models[i] == "ANN") {
    for(j in 1:4) {
      modelname <- paste0("L.",models[i],".",input[j],".char")
      model <- get(modelname)
      model_factor <- factor(model, levels = levels(Ltrain$L_tg))
      cm_table <- confusionMatrix(model_factor, Ltest$L_tg)
      
      
      count.matrix[[j]] <- cm_table$table
      count.matrix[[j]] <- cbind( count.matrix[[j]], Sum=rowSums( count.matrix[[j]]))
      count.matrix[[j]] <- rbind( count.matrix[[j]], Sum=colSums( count.matrix[[j]]))
       
      #percent.matrix[[j]] <- count.matrix[[j]] / sum(cm_table$table)
      percent.matrix[[j]] <- count.matrix[[j]] / c(rowSums(cm_table$table),0)
      percent.matrix[[j]][is.nan(percent.matrix[[j]])] <-0
      percent.matrix[[j]][is.infinite(percent.matrix[[j]])] <-0
      percent.matrix[[j]][,nrow(percent.matrix[[j]])] <- NA
      percent.matrix[[j]][ncol(percent.matrix[[j]]),] <- NA
      
      count.matrix[[j]] <- melt(count.matrix[[j]])
      percent.matrix[[j]] <- melt(percent.matrix[[j]])
      
      
      fig7data[[j]] <- mutate(group_by(as.data.frame(cm_table$table), Reference),
                              percentage = Freq/sum(Freq)*100)
      accu_each <- as.data.frame(cm_table$overall[c(1, 3:4)])
      accu_each <- rbind.data.frame(accu_each, models[i], input[j])
      colnames(accu_each) <- modelname
      accu_L <- cbind.data.frame(accu_L, accu_each)
      }
    }
  else {
      for(j in 1:4) {
        modelname <- (paste0("L.",models[i], ".", input[j],".nocv"))
        model <- get(modelname)
        cm_table <- confusionMatrix(predict(model, newdata = Ltest), Ltest$L_tg)
        
        
        count.matrix[[j+(4*(i-1))]] <- cm_table$table
      count.matrix[[j+(4*(i-1))]] <- cbind( count.matrix[[j+(4*(i-1))]], Sum=rowSums( count.matrix[[j+(4*(i-1))]]))
      count.matrix[[j+(4*(i-1))]] <- rbind( count.matrix[[j+(4*(i-1))]], Sum=colSums( count.matrix[[j+(4*(i-1))]]))
       
	  #percent.matrix[[j+(4*(i-1))]] <- count.matrix[[j+(4*(i-1))]] / sum(cm_table$table)
      percent.matrix[[j+(4*(i-1))]] <- count.matrix[[j+(4*(i-1))]] / c(rowSums(cm_table$table),0)
      percent.matrix[[j+(4*(i-1))]][is.nan(percent.matrix[[j+(4*(i-1))]])] <-0
      percent.matrix[[j+(4*(i-1))]][is.infinite(percent.matrix[[j+(4*(i-1))]])] <-0
      percent.matrix[[j+(4*(i-1))]][,nrow(percent.matrix[[j+(4*(i-1))]])] <- NA
      percent.matrix[[j+(4*(i-1))]][ncol(percent.matrix[[j+(4*(i-1))]]),] <- NA
      
      count.matrix[[j+(4*(i-1))]] <- melt(count.matrix[[j+(4*(i-1))]])
      percent.matrix[[j+(4*(i-1))]] <- melt(percent.matrix[[j+(4*(i-1))]])
        
        
        fig7data[[j+(4*(i-1))]] <- mutate(group_by(as.data.frame(cm_table$table), Reference),
                              percentage = Freq/sum(Freq)*100)
        accu_each <- as.data.frame(cm_table$overall[c(1, 3:4)])
        accu_each <- rbind.data.frame(accu_each, models[i], input[j])
        colnames(accu_each) <- modelname
        accu_L <- cbind.data.frame(accu_L, accu_each)
        }
  }
}


for(i in 1:12){
  fig7[[i]]<-ggplot(data = fig7data[[i]],aes(x=Prediction, y=Reference), fill=percentage) + geom_tile(aes(fill=percentage)) +
  scale_y_discrete(limits = rev(levels(fig7data[[i]]$Reference)), labels=rev(Lline_name), position = "right") +
  scale_x_discrete(labels=Lline_name)  +
  scale_fill_gradient2(mid = "lightgoldenrodyellow", high = "firebrick2", limits = c(0, 100))+geom_text(label=fig7data[[i]]$Freq) + theme(plot.title = element_blank(),
          axis.title = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank(), 
          panel.background = element_blank(), 
          legend.position = "none") 
}

fig7[[1]] <- fig7[[1]] + scale_x_discrete(position = "top") + scale_y_discrete(limits = rev(levels(fig7data[[i]]$Reference)), labels=rev(Lline_name), position = "left") + labs(x = "Full", y = "ANN") + theme(axis.title = element_text(size = rel(1.5)))
fig7[[2]] <- fig7[[2]] + scale_x_discrete(position = "top")+labs(x = "Long") + theme(axis.title = element_text(size = rel(1.5)), axis.title.y = element_blank())
fig7[[3]] <- fig7[[3]] + scale_x_discrete(position = "top")+labs(x = "Short") + theme(axis.title = element_text(size = rel(1.5)), axis.title.y = element_blank())
fig7[[4]] <- fig7[[4]] + scale_x_discrete(position = "top")+labs(x = "Ramp") + theme(axis.title = element_text(size = rel(1.5)), axis.title.y = element_blank(), axis.ticks.y.right = element_line(), axis.text.y.right = element_text(hjust=0, vjust = 0.5))

fig7[[5]] <- fig7[[5]] + scale_y_discrete(limits = rev(levels(fig7data[[i]]$Reference)), labels=rev(Lline_name), position = "left") + labs(y = "LASSO") + theme(axis.title = element_text(size = rel(1.5)), axis.title.x = element_blank())

fig7[[8]] <- fig7[[8]] + theme(axis.ticks.y.right = element_line(), axis.text.y.right = element_text(hjust=0, vjust = 0.5))

fig7[[9]] <- fig7[[9]] + scale_y_discrete(limits = rev(levels(fig7data[[i]]$Reference)), labels=rev(Lline_name), position = "left") + labs(y = "RF") + theme(axis.title = element_text(size = rel(1.5)), axis.title.x = element_blank())

fig7[[12]] <- fig7[[12]] + theme(axis.ticks.y.right = element_line(), axis.text.y.right = element_text(hjust=0, vjust = 0.5))

fig7_u_grob <-lapply(fig7, ggplotGrob)
fig7_u_grob
fig7_cm_wolegend <- grid.arrange(grobs = fig7_u_grob, ncol = 4, nrow = 3, heights = c(1,0.9,0.9), widths = c(1, 0.9, 0.9, 1.1))

legend_fig <- ggplot(data = fig7data[[2]],aes(x=Prediction, y=Reference), fill=percentage) + geom_tile(aes(fill=percentage)) +
  scale_y_discrete(limits = rev(levels(fig7data[[i]]$Reference)), labels=rev(Lline_name), position = "right") +
  scale_x_discrete(labels=Lline_name)  +
  scale_fill_gradient2(mid = "lightgoldenrodyellow", high = "firebrick2", limits = c(0, 100))+geom_text(label=fig7data[[i]]$Freq) + theme(plot.title = element_blank(),
          axis.title = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank(), 
          panel.background = element_blank(), 
          legend.position = "right") 
# http://www.sthda.com/english/wiki/wiki.php?id_contents=7930#add-a-common-legend-for-multiple-ggplot2-graphs
get_legend<-function(myggplot){
  tmp <- ggplot_gtable(ggplot_build(myggplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)
}
blankPlot <- ggplot()+geom_blank(aes(1,1)) + 
  cowplot::theme_nothing()

legend <- get_legend(legend_fig)
fig7_cm <- grid.arrange(fig7_cm_wolegend, legend, blankPlot,  ncol = 2, heights = c(12, 1), widths = c(12, 0.9))



#ggsave("fig6cm.tiff", fig7_cm, width = 12, height = 7, units = "in", dpi = 300)




# Accruay bar chart, accurary date was collected above for-loop

accu_L <- cbind.data.frame(accu_L[2:13])
accu_L <- as.data.frame(t(accu_L))
colnames(accu_L) <- c("Accuracy", "LowCI", "UpCI", "Model", "Input")
accu_L$Accuracy <- as.numeric(as.character(accu_L$Accuracy))
accu_L$LowCI <- as.numeric(as.character(accu_L$LowCI))
accu_L$UpCI <- as.numeric(as.character(accu_L$UpCI))
accu_L$Input <- factor(accu_L$Input, levels(accu_L$Input)[c(1,2,4,3)]) # reorder levels of input from alphabetical to experimental, to match with previous curves
levels(accu_L$Model) <- c("ANN", "LASSO", "RF")
levels(accu_L$Input) <- c("Full", "Long", "Short", "Ramp")

fig7_b <- ggplot(data = accu_L, aes(Input, Accuracy, fill = Model)) + 
  geom_bar(stat = "identity", color = "black", position = position_dodge()) +
  geom_errorbar(aes(ymin= LowCI, ymax = UpCI), width= 0.2, position = position_dodge(0.9)) +

  theme_classic() + 
               labs(x = "", y = "Accuracy") +
               theme(legend.position = "bottom",
                     legend.title = element_blank(),
                     legend.margin=margin(t=-0.7, unit='cm'), 
                     legend.text = element_text(margin = margin(l = 5, r = 10, unit = "pt"))) +
               scale_fill_brewer( palette = "Set1")

#ggsave("fig6accubar.tiff", fig7_b, width = 12, height = 7, units = "in", dpi = 300)


#fig7 <- grid.arrange(fig7_cm, fig7_b, ncol = 1, heights = c(2,1))

#ggsave("fig6.tiff", fig7, width = 12, height = 10, units = "in", dpi = 300)
#ggsave("test.pdf", fig7, width = 12, height = 10, units = "in")
```

```{r}

# code modified 

temp.percent <- data.frame()
for (i in 1:12) {temp.percent <- rbind(temp.percent,percent.matrix[[i]])}
temp.count <- data.frame()
for (i in 1:12) {temp.count <- rbind(temp.count ,count.matrix[[i]])}
dataset <- cbind(temp.percent,temp.count[3])
colnames(dataset) <- c("Predicted","Actual","Proportion","Count")
dataset <- data.frame(dataset,Model=c(rep("ANN",nrow(percent.matrix[[1]])*4),rep("LASSO",nrow(percent.matrix[[1]])*4),rep("RF",nrow(percent.matrix[[1]])*4)),Feature=c(rep(c(rep("Full",nrow(percent.matrix[[1]])),rep("Long",nrow(percent.matrix[[1]])),rep("Short",nrow(percent.matrix[[1]])),rep("Ramp",nrow(percent.matrix[[1]]))),3)))
dataset$Feature <- factor(dataset$Feature, levels = c("Full" , "Long"  ,"Short",  "Ramp"))



```
```{r}
levels(accu_L$Model) <- c("ANN    ", "LASSO  ", "RF     ")
Lline_name <- c("L2/3_Cre","L4_Cre","L5_Cre","L6a_Cre", "L6b_Cre", "Sum")
fontsize=12
theme_set(theme_bw(base_size = fontsize)) 

fig4_modified <- ggplot(data=dataset, aes(x=Predicted,y=Actual), fill=Proportion) +                 
                geom_tile(aes(fill=Proportion)) + geom_text(aes(label=Count),size=2.5) +  
      scale_y_discrete(limits=rev(levels(dataset$Predicted)),position="right") +
  scale_x_discrete(limits=levels(dataset$Predicted), labels=Lline_name, position="right") +
      #scale_fill_gradientn(colours = c("#FFFFFF","blue", "green", "yellow", "yellow","yellow","yellow","red","red","red","red"),breaks = c(0,0.25,0.5,0.75,1), limits=c(0,1), name="Percent of total  ") +
  scale_fill_gradientn(colours = c("#F9F9D1","#E41A1C"),breaks = c(0,0.25,0.5,0.75,1), limits=c(0,1), name="Percent of ??  ",na.value ="#EEEEEE") + 
  geom_vline(xintercept = length(Lline_name)-0.5,size=0.25) + geom_hline(yintercept = 1.5,size=0.25) +
    theme(axis.text.y = element_blank(),
          axis.title= element_text(size=rel(0.9)),
          axis.title.y.right  = element_text(angle=90),
          axis.text.x = element_text(angle=45,hjust=1, size=rel(0.8)),
          axis.ticks = element_blank(), 
          axis.line = element_blank(),
          panel.grid = element_blank(), 
          legend.position = "bottom",
          legend.key.height=unit(0.25,"cm"),
          legend.text = element_text(size=rel(0.5)),
          legend.title=element_text(size=rel(0.8)),
          plot.margin=margin(c(0.2,0.2,0.2,1.1), unit='cm')) + 
          facet_grid(Model~Feature,switch="y")

# legend processing
get_legend<-function(myggplot){
  tmp <- ggplot_gtable(ggplot_build(myggplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)
}


fig7_b <- ggplot(data = accu_L, aes(Input, Accuracy, fill = Model)) + 
  geom_bar(stat = "identity", color = "black", position = position_dodge(width=0.8),width=0.8) +
  geom_errorbar(aes(ymin= LowCI, ymax = UpCI), width= 0.2, position = position_dodge(width=0.8)) +
  scale_y_continuous(expand = c(0,0), limits=c(0,0.85)) +
  theme_bw() + 
               labs(x = "", y = "Accuracy") +
               theme(legend.position = "bottom",
                     legend.title = element_blank(),
                     legend.key.height=unit(0.3,"cm"),
                     legend.key.width=unit(0.3,"cm"),
                     legend.text = element_text(size=rel(0.7),margin = margin(l=0.1, r = 0.1, unit = "cm")),
                     panel.grid = element_blank(),
                     panel.border = element_blank(),
                     axis.line=element_line(),
                     plot.margin=margin(c(0.2,0.4,0.2,0.2), unit='cm')
                     ) +
               scale_fill_brewer( palette = "Set1")


legend1 <- get_legend(fig4_modified)
fig4_modified <- fig4_modified + theme(legend.position = "none")
legend2 <- get_legend(fig7_b)
fig7_b <- fig7_b + theme(legend.position = "none")


fig5 <- grid.arrange(fig4_modified, legend1, legend2, fig7_b, ncol = 2, nrow=3, heights = c(2,0.2,1), widths=c(1.5,1) ,layout_matrix=rbind(c(1,1),c(2,3),c(4,4)))

#ggsave("fig4_modified.pdf", fig5, width = 7.4, height = 9, units = "in")

library(ggpubr)


p <- as_ggplot(fig5) +  draw_plot_label(label = c("A", "B"), size = 15,                  x = c(0,0), y = c(1,0.34)) #

ggsave("SF5_modified_colsum.pdf", p, width = 7.4, height = 9, units = "in")

```



