---
title: "Allen brain data diving train and test set"
output: html_document
author: "Incheol, Hyunsu"
---

# Dataset load
```{r, echo=TRUE, message=FALSE, warning=FALSE}
setwd("/media/hyunsu/data HDD/01.Data&Analysis/clustering_allen_neuron/Data_prep")
cre <- read.csv("ephys_data_cre.csv",header=T)
cre_na_omitted <- na.omit(cre)
cre_na_omitted <- cre_na_omitted[-43] # cre_reporter_status 제거
```

# pulling data subset
```{r, echo=TRUE, message=FALSE, warning=FALSE}
Bset <- cre_na_omitted[-42]   # binary raw data
Eset <- subset(cre_na_omitted[-44],cre_na_omitted$binary_neuron=="Excitatory")
Iset <- subset(cre_na_omitted[-44],cre_na_omitted$binary_neuron=="Inhibitory")
Eset$transgenic_line <- factor(Eset$transgenic_line)  # Transgenic(Excitatory) raw data
Iset$transgenic_line <- factor(Iset$transgenic_line)  # Transgenic(Inhibitory) raw data
```

# train/test data split(stratified)
```{r, echo=TRUE, message=FALSE, warning=FALSE}
# install.packages("caret", repos = "http://cran.r-project.org", dependencies = c("Depends", "Imports", "Suggests"))
library(caret)
BindexTrain <- createDataPartition(Bset$binary_neuron, p = .8, list = F)
Btrain <- Bset[ BindexTrain, ]
Btest  <- Bset[-BindexTrain, ]

EindexTrain <- createDataPartition(Eset$transgenic_line, p = .8, list = F)
Etrain <- Eset[ EindexTrain, ]
Etest  <- Eset[-EindexTrain, ]

IindexTrain <- createDataPartition(Iset$transgenic_line, p = .8, list = F)
Itrain <- Iset[ IindexTrain, ]
Itest  <- Iset[-IindexTrain, ]
```

# Plot the probabilty plot, check the class propotion between train and test set.
```{r, echo=TRUE, message=FALSE, warning=FALSE}
par(mfrow = c(3, 2))
barplot(prop.table(table(Btrain$binary))) 
barplot(prop.table(table(Btest$binary))) 
barplot(prop.table(table(Etrain$transgenic_line))) 
barplot(prop.table(table(Etest$transgenic_line))) 
barplot(prop.table(table(Itrain$transgenic_line))) 
barplot(prop.table(table(Itest$transgenic_line))) 
```

# Draw pie chart for supple figure, stratified class division
```{r, echo=TRUE, message=FALSE, warning=FALSE}
require(ggplot2)
Btrain_df <- as.data.frame(table(Btrain$binary))
 # theme_set(theme_classic())

DrawPieChart <- function(data_class){
  df <- as.data.frame(table(data_class))
  data_title <- deparse(substitute(data_class))
  return(ggplot(df, aes(x = "", y = Freq, 
                        fill = factor(data_class))) +
           geom_bar(width = 1, stat = "identity") +
           theme(axis.line = element_blank(), 
                 plot.title = element_text(hjust=0.5),
                # axis.text.x=element_blank(), 
                 axis.ticks = element_blank()) +
           labs(fill="", x=NULL, y=NULL, title= data_title) +
           coord_polar(theta = "y", start = 0) +
           scale_fill_brewer(palette = "RdYlBu"))
}

Btra_pie <- DrawPieChart(Btrain$binary)
Btes_pie <- DrawPieChart(Btest$binary)
Etra_pie <- DrawPieChart(Etrain$transgenic_line)
Etes_pie <- DrawPieChart(Etest$transgenic_line)
Itra_pie <- DrawPieChart(Itrain$transgenic_line)
Ites_pie <- DrawPieChart(Itest$transgenic_line)

require(grid)
require(gridExtra)
require(Cairo)

pie <- grid.arrange(Btra_pie,Btes_pie,Etra_pie,Etes_pie,Itra_pie,Ites_pie,
                    ncol=2)
ggsave("piechart.tiff", plot = pie, units = "in", width = 8, height = 12, dpi =300)
```

# subset data generation according to electrophysiological stimuli method
```{r, echo=TRUE, message=FALSE, warning=FALSE}
subsetgeneration <-function(dataset, type) {
  if (type=="l") return(dataset[-c(5,6,8,9,13,14,16,17,20,21,23,24,26,27,29,30,32,33,35,36,38,39)])
  if (type=="s") return(dataset[-c(4,5,7,8,12,13,15,16,22,23,25,26,28,29,31,32,34,35,37,38)])
  if (type=="r") return(dataset[-c(4,6,7,9,12,14,15,17,20,21,22,24,25,27,28,30,31,33,34,36,37,39)])
}

Btrain.l <- subsetgeneration(Btrain,"l")
Btrain.s <- subsetgeneration(Btrain,"s")
Btrain.r <- subsetgeneration(Btrain,"r")

Btest.l <- subsetgeneration(Btest,"l")
Btest.s <- subsetgeneration(Btest,"s")
Btest.r <- subsetgeneration(Btest,"r")

Etrain.l <- subsetgeneration(Etrain,"l")
Etrain.s <- subsetgeneration(Etrain,"s")
Etrain.r <- subsetgeneration(Etrain,"r")

Etest.l <- subsetgeneration(Etest,"l")
Etest.s <- subsetgeneration(Etest,"s")
Etest.r <- subsetgeneration(Etest,"r")

Itrain.l <- subsetgeneration(Itrain,"l")
Itrain.s <- subsetgeneration(Itrain,"s")
Itrain.r <- subsetgeneration(Itrain,"r")

Itest.l <- subsetgeneration(Itest,"l")
Itest.s <- subsetgeneration(Itest,"s")
Itest.r <- subsetgeneration(Itest,"r")

```

# write divided data into csv file
```{r, echo=TRUE, message=FALSE, warning=FALSE}
setwd("./divided_data/")
write.csv(Btrain,"Btrain.csv")
write.csv(Btrain.l,"Btrain_long.csv")
write.csv(Btrain.s,"Btrain_short.csv")
write.csv(Btrain.r,"Btrain_ramp.csv")

write.csv(Btest,"Btest.csv")
write.csv(Btest.l,"Btest_long.csv")
write.csv(Btest.s,"Btest_short.csv")
write.csv(Btest.r,"Btest_ramp.csv")

write.csv(Etrain,"Etrain.csv")
write.csv(Etrain.l,"Etrain_long.csv")
write.csv(Etrain.s,"Etrain_short.csv")
write.csv(Etrain.r,"Etrain_ramp.csv")

write.csv(Etest,"Etest.csv")
write.csv(Etest.l,"Etest_long.csv")
write.csv(Etest.s,"Etest_short.csv")
write.csv(Etest.r,"Etest_ramp.csv")

write.csv(Itrain,"Itrain.csv")
write.csv(Itrain.l,"Itrain_long.csv")
write.csv(Itrain.s,"Itrain_short.csv")
write.csv(Itrain.r,"Itrain_ramp.csv")

write.csv(Itest,"Itest.csv")
write.csv(Itest.l,"Itest_long.csv")
write.csv(Itest.s,"Itest_short.csv")
write.csv(Itest.r,"Itest_ramp.csv")
```




