---
title: "binary classification model making(LASSO and RF)"
author: "incheol, hyunsu"
date: "July 24, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data load

```{r, message=FALSE, warning=FALSE}
setwd("../Data_prep/divided_revised_data")

cre_na_omitted <- read.csv("../Data_prep/divided_revised_data/cre_na_omitted.csv", row.names = "X")

Btrain		<- read.csv("../Data_prep/divided_revised_data/Btrain.csv", row.names = "X")
Btrain.l	<- read.csv("../Data_prep/divided_revised_data/Btrain_long.csv", row.names = "X")
Btrain.s	<- read.csv("../Data_prep/divided_revised_data/Btrain_short.csv", row.names = "X")
Btrain.r	<- read.csv("../Data_prep/divided_revised_data/Btrain_ramp.csv", row.names = "X")

Btest		<- read.csv("../Data_prep/divided_revised_data/Btest.csv", row.names = "X")
Btest.l		<- read.csv("../Data_prep/divided_revised_data/Btest_long.csv", row.names = "X")
Btest.s		<- read.csv("../Data_prep/divided_revised_data/Btest_short.csv", row.names = "X")
Btest.r		<- read.csv("../Data_prep/divided_revised_data/Btest_ramp.csv", row.names = "X")
```

# Binary prediction (E vs I)
```{r, message=FALSE, warning=FALSE}
require(ROCR)
x.conven <- cre_na_omitted$firing_rate # Firing rate are normally adapted for fearture classification E vs I.
preds = (x.conven-min(x.conven))/(max(x.conven)-min(x.conven)) # conversion to probability

conventional.pred = prediction(preds,cre_na_omitted$binary_neuron)
conventional.perf = performance(conventional.pred,"tpr","fpr")
conventional.auc  =performance(conventional.pred,'auc')
```

# set Cross-validation as k-fold
```{r, message=FALSE, warning=FALSE}
require(caret)
fitControl <- trainControl(method = "repeatedcv", number = 10, repeats = 5)
noCV <- trainControl(method = "none")

tuneGrid <- expand.grid(alpha = 1, lambda = seq(0.0001, 1, length = 10))
noGrid <- expand.grid(alpha = 1, lambda = 0.01)
```

# LASSO training
```{r, message=FALSE, warning=FALSE}
doMC::registerDoMC(cores = 4) # multi core calculation

set.seed(849)

B.reg.full.cv <- caret::train(binary_neuron ~ ., data = Btrain, method = "glmnet", trControl = fitControl, tuneGrid = tuneGrid)
B.reg.full.nocv <-caret::train(binary_neuron ~ ., data = Btrain, method = "glmnet", trControl = noCV, tuneGrid = noGrid)

B.reg.long.cv <- caret::train(binary_neuron ~ ., data = Btrain.l, method = "glmnet", trControl = fitControl, tuneGrid = tuneGrid)
B.reg.long.nocv <-caret::train(binary_neuron ~ ., data = Btrain.l, method = "glmnet", trControl = noCV, tuneGrid = noGrid)

B.reg.short.cv <- caret::train(binary_neuron ~ ., data = Btrain.s, method = "glmnet", trControl = fitControl, tuneGrid = tuneGrid)
B.reg.short.nocv <-caret::train(binary_neuron ~ ., data = Btrain.s, method = "glmnet", trControl = noCV, tuneGrid = noGrid)

B.reg.ramp.cv <- caret::train(binary_neuron ~ ., data = Btrain.r, method = "glmnet", trControl = fitControl, tuneGrid = tuneGrid)
B.reg.ramp.nocv <-caret::train(binary_neuron ~ ., data = Btrain.r, method = "glmnet", trControl = noCV, tuneGrid = noGrid)
```

# Prediction accuracy of LASSO model
```{r, message=FALSE, warning=FALSE}
library(magrittr)

cat("\n\n\n--------- Binary prediction / Full model / LASSO with CV ----------\n")
a<-predict(B.reg.full.cv, newdata = Btest) %>% confusionMatrix(Btest$binary_neuron)
a$table
cat("\n")
a$overall[c(1,3:4)]

cat("\n\n\n--------- Binary prediction / Full model / LASSO without CV ----------\n")
a<-predict(B.reg.full.nocv, newdata = Btest) %>% confusionMatrix(Btest$binary_neuron)
a$table
cat("\n")
a$overall[c(1,3:4)]

cat("\n\n\n--------- Binary prediction / Long model / LASSO with CV ----------\n")
a<-predict(B.reg.long.cv, newdata = Btest.l) %>% confusionMatrix(Btest$binary_neuron)
a$table
cat("\n")
a$overall[c(1,3:4)]

cat("\n\n\n--------- Binary prediction / Long model / LASSO without CV ----------\n")
a<-predict(B.reg.long.nocv, newdata = Btest.l) %>% confusionMatrix(Btest$binary_neuron)
a$table
cat("\n")
a$overall[c(1,3:4)]

cat("\n\n\n--------- Binary prediction / Short model / LASSO with CV ----------\n")
a<-predict(B.reg.short.cv, newdata = Btest.s) %>% confusionMatrix(Btest$binary_neuron)
a$table
cat("\n")
a$overall[c(1,3:4)]

cat("\n\n\n--------- Binary prediction / Short model / LASSO without CV ----------\n")
a<-predict(B.reg.short.nocv, newdata = Btest.s) %>% confusionMatrix(Btest$binary_neuron)
a$table
cat("\n")
a$overall[c(1,3:4)]

cat("\n\n\n--------- Binary prediction / Ramp model / LASSO with CV ----------\n")
a<-predict(B.reg.ramp.cv, newdata = Btest.r) %>% confusionMatrix(Btest$binary_neuron)
a$table
cat("\n")
a$overall[c(1,3:4)]

cat("\n\n\n--------- Binary prediction / Ramp model / LASSO without CV ----------\n")
a<-predict(B.reg.ramp.nocv, newdata = Btest.r) %>% confusionMatrix(Btest$binary_neuron)
a$table
cat("\n")
a$overall[c(1,3:4)]
```

# Plotting ROC curve & AUC
```{r, message=FALSE, warning=FALSE}
Broc <- function(model,dataset) {
preds = predict(model,type="prob",newdata=dataset)[,2]
pred = prediction(preds,Btest$binary_neuron)
au<-performance(pred,"auc")
cat(substitute(model),": ",au@y.values[[1]],"\n")
return(performance(pred,"tpr","fpr"))
}

plot(conventional.perf,col=2,lwd=0.5,main="ROC Curves (LASSO)")
plot(Broc(B.reg.full.cv,Btest),col=3,lwd=0.5,add=T)
plot(Broc(B.reg.full.nocv,Btest),col=4,lwd=0.5,add=T)
plot(Broc(B.reg.long.cv,Btest.l),col=5,lwd=0.5,add=T)
plot(Broc(B.reg.long.nocv,Btest.l),col=6,lwd=0.5,add=T)
plot(Broc(B.reg.short.cv,Btest.s),col=7,lwd=0.5,add=T)
plot(Broc(B.reg.short.nocv,Btest.s),col=8,lwd=0.5,add=T)
plot(Broc(B.reg.ramp.cv,Btest.r),col=9,lwd=0.5,add=T)
plot(Broc(B.reg.ramp.nocv,Btest.r),col=10,lwd=0.5,add=T)
abline(a=0,b=1,lwd=1,lty=2,col="gray")
legend("bottomright",col=c(2:10),lwd=2,legend=c("firing_rate","full_CV","full_noCV","long_CV","long_noCV","short_CV","short_noCV","ramp_CV","ramp_noCV"),bty='n') 
```

# Random forest training
```{r, message=FALSE, warning=FALSE}
doMC::registerDoMC(cores = 4) # multi core calculation

set.seed(849)

B.rf.full.cv <- caret::train(binary_neuron ~ ., data = Btrain, method = "rf", trControl = fitControl)
B.rf.full.nocv <-caret::train(binary_neuron ~ ., data = Btrain, method = "rf", trControl = noCV)

B.rf.long.cv <- caret::train(binary_neuron ~ ., data = Btrain.l, method = "rf", trControl = fitControl)
B.rf.long.nocv <-caret::train(binary_neuron ~ ., data = Btrain.l, method = "rf", trControl = noCV)

B.rf.short.cv <- caret::train(binary_neuron ~ ., data = Btrain.s, method = "rf", trControl = fitControl)
B.rf.short.nocv <-caret::train(binary_neuron ~ ., data = Btrain.s, method = "rf", trControl = noCV)

B.rf.ramp.cv <- caret::train(binary_neuron ~ ., data = Btrain.r, method = "rf", trControl = fitControl)
B.rf.ramp.nocv <-caret::train(binary_neuron ~ ., data = Btrain.r, method = "rf", trControl = noCV)
```

# Prediction accuracy of RF models
```{r, message=FALSE, warning=FALSE}
library(magrittr)


cat("\n\n\n--------- Binary prediction / Full model / RANDOM FOREST with CV ----------\n")
a<-predict(B.rf.full.cv, newdata = Btest) %>% confusionMatrix(Btest$binary_neuron)
a$table
cat("\n")
a$overall[c(1,3:4)]

cat("\n\n\n--------- Binary prediction / Full model / RANDOM FOREST without CV ----------\n")
a<-predict(B.rf.full.nocv, newdata = Btest) %>% confusionMatrix(Btest$binary_neuron)
a$table
cat("\n")
a$overall[c(1,3:4)]

cat("\n\n\n--------- Binary prediction / Long model / RANDOM FOREST with CV ----------\n")
a<-predict(B.rf.long.cv, newdata = Btest.l) %>% confusionMatrix(Btest$binary_neuron)
a$table
cat("\n")
a$overall[c(1,3:4)]

cat("\n\n\n--------- Binary prediction / Long model / RANDOM FOREST without CV ----------\n")
a<-predict(B.rf.long.nocv, newdata = Btest.l) %>% confusionMatrix(Btest$binary_neuron)
a$table
cat("\n")
a$overall[c(1,3:4)]

cat("\n\n\n--------- Binary prediction / Short model / RANDOM FOREST with CV ----------\n")
a<-predict(B.rf.short.cv, newdata = Btest.s) %>% confusionMatrix(Btest$binary_neuron)
a$table
cat("\n")
a$overall[c(1,3:4)]

cat("\n\n\n--------- Binary prediction / Short model / RANDOM FOREST without CV ----------\n")
a<-predict(B.rf.short.nocv, newdata = Btest.s) %>% confusionMatrix(Btest$binary_neuron)
a$table
cat("\n")
a$overall[c(1,3:4)]

cat("\n\n\n--------- Binary prediction / Ramp model / RANDOM FOREST with CV ----------\n")
a<-predict(B.rf.ramp.cv, newdata = Btest.r) %>% confusionMatrix(Btest$binary_neuron)
a$table
cat("\n")
a$overall[c(1,3:4)]

cat("\n\n\n--------- Binary prediction / Ramp model / RANDOM FOREST without CV ----------\n")
a<-predict(B.rf.ramp.nocv, newdata = Btest.r) %>% confusionMatrix(Btest$binary_neuron)
a$table
cat("\n")
a$overall[c(1,3:4)]
```


# Plot ROC curve & AUC
```{r, message=FALSE, warning=FALSE}
library(ROCR)
Broc <- function(model,dataset) {
preds = predict(model,type="prob",newdata=dataset)[,2]
pred = prediction(preds,Btest$binary_neuron)
au<-performance(pred,"auc")
cat(substitute(model),": ",au@y.values[[1]],"\n")
return(performance(pred,"tpr","fpr"))
}

plot(conventional.perf,col=2,lwd=0.5,main="ROC Curves (RANDOM FOREST)")
plot(Broc(B.rf.full.cv,Btest),col=3,lwd=0.5,add=T)
plot(Broc(B.rf.full.nocv,Btest),col=4,lwd=0.5,add=T)
plot(Broc(B.rf.long.cv,Btest.l),col=5,lwd=0.5,add=T)
plot(Broc(B.rf.long.nocv,Btest.l),col=6,lwd=0.5,add=T)
plot(Broc(B.rf.short.cv,Btest.s),col=7,lwd=0.5,add=T)
plot(Broc(B.rf.short.nocv,Btest.s),col=8,lwd=0.5,add=T)
plot(Broc(B.rf.ramp.cv,Btest.r),col=9,lwd=0.5,add=T)
plot(Broc(B.rf.ramp.nocv,Btest.r),col=10,lwd=0.5,add=T)
abline(a=0,b=1,lwd=1,lty=2,col="gray")
legend("bottomright",col=c(2:10),lwd=2,legend=c("firing_rate","full_CV","full_noCV","long_CV","long_noCV","short_CV","short_noCV","ramp_CV","ramp_noCV"),bty='n') 
```

# Saving models
```{r, message=FALSE, warning=FALSE}
save(B.reg.full.cv, file = "./R_models/B.reg.full.cv.rda")
save(B.reg.full.nocv, file = "./R_models/B.reg.full.nocv.rda")

save(B.reg.long.cv, file = "./R_models/B.reg.long.cv.rda")
save(B.reg.long.nocv, file = "./R_models/B.reg.long.nocv.rda")

save(B.reg.short.cv, file = "./R_models/B.reg.short.cv.rda")
save(B.reg.short.nocv, file = "./R_models/B.reg.short.nocv.rda")

save(B.reg.ramp.cv, file = "./R_models/B.reg.ramp.cv.rda")
save(B.reg.ramp.nocv, file = "./R_models/B.reg.ramp.nocv.rda")

save(B.rf.full.cv, file = "./R_models/B.rf.full.cv.rda")
save(B.rf.full.nocv, file = "./R_models/B.rf.full.nocv.rda")

save(B.rf.long.cv, file = "./R_models/B.rf.long.cv.rda")
save(B.rf.long.nocv, file = "./R_models/B.rf.long.nocv.rda")

save(B.rf.short.cv, file = "./R_models/B.rf.short.cv.rda")
save(B.rf.short.nocv, file = "./R_models/B.rf.short.nocv.rda")

save(B.rf.ramp.cv, file = "./R_models/B.rf.ramp.cv.rda")
save(B.rf.ramp.nocv, file = "./R_models/B.rf.ramp.nocv.rda")

```


