#python3 00_4_binary_full_restore.py &&
#python3 01_4_binary_long_restore.py &&
#python3 02_4_binary_short_restore.py &&
#python3 03_4_binary_ramp_restore.py &&
#python3 04_4_Eline_full_restore.py &&
#python3 05_4_Eline_long_restore.py &&
#python3 06_4_Eline_short_restore.py &&
#python3 07_4_Eline_ramp_restore.py &&
#python3 08_4_Iline_full_restore.py &&
#python3 09_4_Iline_long_restore.py &&
#python3 10_4_Iline_short_restore.py &&
#python3 11_4_Iline_ramp_restore.py &&
python3 12_4_Lline_full_restore.py &&
python3 13_4_Lline_long_restore.py &&
python3 14_4_Lline_short_restore.py &&
python3 15_4_Lline_ramp_restore.py &&
python3 04_4_Eline_full_restore_notmerged.py &&
python3 05_4_Eline_long_restore_notmerged.py &&
python3 06_4_Eline_short_restore_notmerged.py &&
python3 07_4_Eline_ramp_restore_notmerged.py &&
python3 08_4_Iline_full_restore_notmerged.py &&
python3 09_4_Iline_long_restore_notmerged.py &&
python3 10_4_Iline_short_restore_notmerged.py &&
python3 11_4_Iline_ramp_restore_notmerged.py 
